import Head from 'next/head';
import Hero from '@/components/home/Hero';
import About from '@/components/home/About';
import Portfolio from '@/components/home/Portfolio';
import Service from '@/components/home/Services';
import CallToAction from '@/components/home/CallToAction';
import Testimonies from '@/components/home/Testimonies';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jappar Draws</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <Hero />
        <About />
        <Service />
        <Portfolio />
        <Testimonies />
        <CallToAction />
      </main>
    </>
  );
}
