import Head from 'next/head';
import styles from '@/styles/pages/Home.module.css';
import Hero from '@/components/home/Hero';
import Summary from '@/components/home/Summary';
import Works from '@/components/home/Works';
import Commissions from '@/components/home/Commissions';
import DoAndDont from '@/components/home/DoAndDont';
import TermsOfService from '@/components/home/TermsOfService';
import Order from '@/components/home/Order';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jappar Draws</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <Hero />
        <Summary />
        <Works />
        <Commissions />
        <DoAndDont />
        <TermsOfService />
        <Order />
      </main>
    </>
  );
}
